'''
Date: 2021.03.07 22:24:00
LastEditors: Rustle Karl
LastEditTime: 2021.03.07 22:28:36
'''
from pathlib import Path

_dst = Path(__file__).absolute().parent / "glsl"


class GLTransition(object):
    Angular = _dst / "angular.glsl"
    Bounce = _dst / "Bounce.glsl"
    BowTieHorizontal = _dst / "BowTieHorizontal.glsl"
    BowTieVertical = _dst / "BowTieVertical.glsl"
    BowTieWithParameter = _dst / "BowTieWithParameter.glsl"
    Burn = _dst / "burn.glsl"
    ButterflyWaveScrawler = _dst / "ButterflyWaveScrawler.glsl"
    CannabisLeaf = _dst / "cannabisleaf.glsl"
    Circle = _dst / "circle.glsl"
    CircleCrop = _dst / "CircleCrop.glsl"
    CircleOpen = _dst / "circleopen.glsl"
    ColorPhase = _dst / "colorphase.glsl"
    ColourDistance = _dst / "ColourDistance.glsl"
    CrazyParametricFun = _dst / "CrazyParametricFun.glsl"
    Crosshatch = _dst / "crosshatch.glsl"
    CrossWarp = _dst / "crosswarp.glsl"
    CrossZoom = _dst / "CrossZoom.glsl"
    Cube = _dst / "cube.glsl"
    DirectionalEasing = _dst / "directional-easing.glsl"
    Directional = _dst / "Directional.glsl"
    DirectionalWarp = _dst / "directionalwarp.glsl"
    DirectionalWipe = _dst / "directionalwipe.glsl"
    Displacement = _dst / "displacement.glsl"
    DoomScreenTransition = _dst / "DoomScreenTransition.glsl"
    Doorway = _dst / "doorway.glsl"
    Dreamy = _dst / "Dreamy.glsl"
    DreamyZoom = _dst / "DreamyZoom.glsl"
    Fade = _dst / "fade.glsl"
    FadeColor = _dst / "fadecolor.glsl"
    FadeGrayscale = _dst / "fadegrayscale.glsl"
    FilmBurn = _dst / "FilmBurn.glsl"
    FlyEye = _dst / "flyeye.glsl"
    GlitchDisplace = _dst / "GlitchDisplace.glsl"
    GlitchMemories = _dst / "GlitchMemories.glsl"
    GridFlip = _dst / "GridFlip.glsl"
    Heart = _dst / "heart.glsl"
    Hexagonalize = _dst / "hexagonalize.glsl"
    InvertedPageCurl = _dst / "InvertedPageCurl.glsl"
    Kaleidoscope = _dst / "kaleidoscope.glsl"
    LeftRight = _dst / "LeftRight.glsl"
    LinearBlur = _dst / "LinearBlur.glsl"
    Luma = _dst / "luma.glsl"
    LuminanceMelt = _dst / "luminance_melt.glsl"
    Morph = _dst / "morph.glsl"
    Mosaic = _dst / "Mosaic.glsl"
    MultiplyBlend = _dst / "multiply_blend.glsl"
    Perlin = _dst / "perlin.glsl"
    Pinwheel = _dst / "pinwheel.glsl"
    Pixelize = _dst / "pixelize.glsl"
    PolarFunction = _dst / "polar_function.glsl"
    PolkaDotsCurtain = _dst / "PolkaDotsCurtain.glsl"
    Radial = _dst / "Radial.glsl"
    RandomNoisex = _dst / "randomNoisex.glsl"
    RandomSquares = _dst / "randomsquares.glsl"
    Ripple = _dst / "ripple.glsl"
    RotateScaleFade = _dst / "rotate_scale_fade.glsl"
    SimpleZoom = _dst / "SimpleZoom.glsl"
    SquaresWire = _dst / "squareswire.glsl"
    Squeeze = _dst / "squeeze.glsl"
    StereoViewer = _dst / "StereoViewer.glsl"
    Swap = _dst / "swap.glsl"
    Swirl = _dst / "Swirl.glsl"
    TangentMotionBlur = _dst / "tangentMotionBlur.glsl"
    TopBottom = _dst / "TopBottom.glsl"
    WaterDrop = _dst / "WaterDrop.glsl"
    Wind = _dst / "wind.glsl"
    WindowBlinds = _dst / "windowblinds.glsl"
    WindowSlice = _dst / "windowslice.glsl"
    WipeDown = _dst / "wipeDown.glsl"
    WipeLeft = _dst / "wipeLeft.glsl"
    WipeRight = _dst / "wipeRight.glsl"
    WipeUp = _dst / "wipeUp.glsl"
    ZoomInCircles = _dst / "ZoomInCircles.glsl"


All = [v for k, v in vars(GLTransition).items() if not k.endswith("__")]

if __name__ == '__main__':
    print(All)
